### PR TITLE
[IMPL] AutoWalk

### PR DESCRIPTION
**Pull request by HausemasterIssue**
it's autowalk. kinda useful, i didn't code this with an ide cuz im too lazy so i probably got something wrong, but yeah, lmk what you think.

### CODE REVIEW

**Comment by linustouchtips** [comment]
why not just use baritone? this seems like bloat.

**Comment by linustouchtips** [comment]
correct me if i am wrong, but baritone integration is not possible due to the project's license.

**Comment by linustouchtips** [comment]
you can always use the baritone standalone mod. i don't see how walking in a straight line is useful because highways always have shit on them like holes, or withers, or walls.

**Comment by HausemasterIssue** [comment]
plus there might be lava or fire if your walking in a straight tunnel so, bruh,

**Pull request closed without merging**
